### ISSUE TITLE
Instructions don't work on OS X

### ISSUE THREAD

**Issue by jeremytregunna** [Ogeon/rust-on-raspberry-pi#1]
All the shipped binaries with pi-tools are for Linux, and these instructions make use of running those binaries to generate the cross compiler. This fails for obvious reasons, Mac OS X is not binary compatible with Linux executables.

**Comment by Ogeon** [comment]
That's unfortunate. A quick search gave me [this](http://www.jaredwolff.com/blog/cross-compiling-on-mac-osx-for-raspberry-pi/), but I don't know if it's useful since I don't have any Mac available for testing.

**Comment by Ogeon** [comment]
A pull request with an OS X version of the guide would be hugely appreciated, if you or anyone else would mange to make it work.

**Comment by Ogeon** [comment]
Note that the Docker container works for OS X, so it's an alternative.

**Comment by Ragnaroek** [comment]
Close this one? The docker image solves exactly this issue here (that was the reason for me to use it)

**Comment by Ogeon** [comment]
Hmm, yes, and the guide won't support OS X for a foreseeable future.
