### ISSUE TITLE
Add C++ support to the docker file

### ISSUE THREAD

**Issue by Ogeon** [Ogeon/rust-on-raspberry-pi#16]
As discussed in #15.

**Comment by Ragnaroek** [comment]
I like to close this one, because the docker repo focuses solely on cross-compiling Rust.

**Comment by Ogeon** [comment]
The thing is that there may be C++ dependencies.

**Comment by Ragnaroek** [comment]
Ok, I added the issue to the docker repo. You may close it here.

**Comment by Ogeon** [comment]
Cool!
