### ISSUE TITLE
make/platform/clang_linux.mk:16: *** "unable to infer compiler target triple for gcc".

### ISSUE THREAD

**Issue by apirogov** [Ogeon/rust-on-raspberry-pi#2]
I did exactly what the guide set, it compiled for half an hour and terminated with this error, I'm on Arch Linux.

**Comment by Ogeon** [comment]
Strange. Did you compile the stable or master branch? I have had some problems with the stable branch, but I can't remember seeing this error... Are you able to compile it for the host system?

**Comment by apirogov** [comment]
Ok I tried ./configure && make without modifications, still the same error.
It happens when it compiles compiler-rt:

make[1]: Verzeichnis „/home/admin/bin/rust/src/compiler-rt“ wird betreten
warning: clang_darwin.mk: dropping arch 'i386' from lib 'eprintf' (clang does not support it)
warning: clang_darwin.mk: dropping arch 'i386' from lib '10.4' (clang does not support it)
warning: clang_darwin.mk: dropping arch 'x86_64' from lib '10.4' (clang does not support it)
warning: clang_darwin.mk: dropping arch 'i386' from lib 'ios' (clang does not support it)
warning: clang_darwin.mk: dropping arch 'x86_64' from lib 'ios' (clang does not support it)
warning: clang_darwin.mk: dropping arch 'x86_64h' from lib 'ios' (clang does not support it)
warning: clang_darwin.mk: dropping arch 'armv7' from lib 'ios' (clang does not support it)
warning: clang_darwin.mk: dropping arch 'i386' from lib 'osx' (clang does not support it)
warning: clang_darwin.mk: dropping arch 'x86_64' from lib 'osx' (clang does not support it)
warning: clang_darwin.mk: dropping arch 'x86_64h' from lib 'osx' (clang does not support it)
warning: clang_darwin.mk: dropping arch 'armv7' from lib 'cc_kext' (clang does not support it)
warning: clang_darwin.mk: dropping arch 'i386' from lib 'cc_kext' (clang does not support it)
warning: clang_darwin.mk: dropping arch 'x86_64' from lib 'cc_kext' (clang does not support it)
warning: clang_darwin.mk: dropping arch 'x86_64h' from lib 'cc_kext' (clang does not support it)
warning: clang_darwin.mk: dropping arch 'x86_64' from lib 'cc_kext_ios5' (clang does not support it)
warning: clang_darwin.mk: dropping arch 'x86_64h' from lib 'cc_kext_ios5' (clang does not support it)
warning: clang_darwin.mk: dropping arch 'armv7' from lib 'cc_kext_ios5' (clang does not support it)
warning: clang_darwin.mk: dropping arch 'i386' from lib 'profile_osx' (clang does not support it)
warning: clang_darwin.mk: dropping arch 'x86_64' from lib 'profile_osx' (clang does not support it)
warning: clang_darwin.mk: dropping arch 'x86_64h' from lib 'profile_osx' (clang does not support it)
warning: clang_darwin.mk: dropping arch 'i386' from lib 'profile_ios' (clang does not support it)
warning: clang_darwin.mk: dropping arch 'x86_64' from lib 'profile_ios' (clang does not support it)
warning: clang_darwin.mk: dropping arch 'x86_64h' from lib 'profile_ios' (clang does not support it)
warning: clang_darwin.mk: dropping arch 'armv7' from lib 'profile_ios' (clang does not support it)
warning: clang_darwin.mk: dropping arch 'i386' from lib 'asan_osx_dynamic' (clang does not support it)
warning: clang_darwin.mk: dropping arch 'x86_64' from lib 'asan_osx_dynamic' (clang does not support it)
warning: clang_darwin.mk: dropping arch 'x86_64h' from lib 'asan_osx_dynamic' (clang does not support it)
warning: clang_darwin.mk: dropping arch 'i386' from lib 'ubsan_osx' (clang does not support it)
warning: clang_darwin.mk: dropping arch 'x86_64' from lib 'ubsan_osx' (clang does not support it)
warning: clang_darwin.mk: dropping arch 'x86_64h' from lib 'ubsan_osx' (clang does not support it)
warning: clang_macho_embedded.mk: dropping arch 'armv6m' from lib 'soft_static'
warning: clang_macho_embedded.mk: dropping arch 'armv7m' from lib 'soft_static'
warning: clang_macho_embedded.mk: dropping arch 'armv7em' from lib 'soft_static'
warning: clang_macho_embedded.mk: dropping arch 'armv7' from lib 'soft_static'
warning: clang_macho_embedded.mk: dropping arch 'armv7em' from lib 'hard_static'
warning: clang_macho_embedded.mk: dropping arch 'armv7' from lib 'hard_static'
warning: clang_macho_embedded.mk: dropping arch 'i386' from lib 'hard_static'
warning: clang_macho_embedded.mk: dropping arch 'x86_64' from lib 'hard_static'
warning: clang_macho_embedded.mk: dropping arch 'armv6m' from lib 'soft_pic'
warning: clang_macho_embedded.mk: dropping arch 'armv7m' from lib 'soft_pic'
warning: clang_macho_embedded.mk: dropping arch 'armv7em' from lib 'soft_pic'
warning: clang_macho_embedded.mk: dropping arch 'armv7' from lib 'soft_pic'
warning: clang_macho_embedded.mk: dropping arch 'armv7em' from lib 'hard_pic'
warning: clang_macho_embedded.mk: dropping arch 'armv7' from lib 'hard_pic'
warning: clang_macho_embedded.mk: dropping arch 'i386' from lib 'hard_pic'
warning: clang_macho_embedded.mk: dropping arch 'x86_64' from lib 'hard_pic'
make/platform/clang_linux.mk:16: **\* "unable to infer compiler target triple for gcc".

Which triple would be correct and can I force it somehow? And should I report this at the rust repo?

**Comment by Ogeon** [comment]
Looks similar to [this](http://www.reddit.com/r/rust/comments/1yd2mv/compiling_from_master_unable_to_infer_compiler/). You could try the same workaround.

**Comment by apirogov** [comment]
Thanks for the reference. As it seems to be a compiler-rt issue, I close this.

**Comment by Ogeon** [comment]
Alright :)
