### ISSUE TITLE
publishing the docker image on the docker hub

### ISSUE THREAD

**Issue by Ragnaroek** [Ogeon/rust-on-raspberry-pi#26]
Hi,
I like to publish a prebuilt image of the docker image on the docker hub.
It would allow everyone to pull the image instead of building it self.

You're ok with that?

If you like, I can give you full access to the docker hub repository.

-- Michael

**Comment by Ogeon** [comment]
Sure, I don't mind, but I feel like I have to give most of the credits to @schnupperboy. He made the actual docker file.

That said, I'm not (and has never been) awfully interested in maintaining it, myself, and that has started becoming true for this whole guide. There's always something else taking priority, so I wouldn't actually mind handing it over to someone more enthusiastic. It's better letting someone else give it new life, than holding on to it. Are you interested?

**Comment by Ragnaroek** [comment]
Ok, I would take over but probably would drop the "native" support and 
only keep the docker file.

**Comment by Ogeon** [comment]
Hmm... that's a pity... Perhaps we can make some other arrangement. Maybe just extract the docker part and link to it from here?

**Comment by Ragnaroek** [comment]
Ok, we could link both ways.

I will setup a new repo with the docker stuff (and of course correct 
credits) when I will build
the docker image.

-- Michael

**Comment by Ogeon** [comment]
Sounds great! :+1: Notify me when done, and I'll get that link going, or make a PR with it. That may actually be faster. Do whatever.

**Comment by Ragnaroek** [comment]
The split is now done:
https://github.com/Ragnaroek/rust-on-raspberry-docker is the repo with only the docker stuff.

The prebuild image is on the dockerhub: https://hub.docker.com/r/ragnaroek/rust-raspberry/

and this PR removes the docker stuff from this repo:
https://github.com/Ogeon/rust-on-raspberry-pi/pull/27

Closing this issue :)
