### ISSUE TITLE
Dockerize the process

### ISSUE THREAD

**Issue by junactl** [Ogeon/rust-on-raspberry-pi#5]
Hi,

thx a lot for documenting the whole cross compilation process here! However, I'd like to isolate this process and run it inside a docker container in order for my workstation to stay clean and be able to remove all the env vars and configurations one has to make.

I thought about creating a Dockerfile which:
- clones the rust & pi-tools git repos inside the docker image
- sets all needed configs and env vars as specified in the README.md
- compiles the rust cross compiler
- cross compiles a given rust project, also considering optional given binary dependencies 

When running the container with the created image the only things to do are:
- mount a host directory into the container (the individual rust project you want to cross compile)
- optional: mount another host directory into the container including all binary dependencies as .deb files you need (e.g. openssl)
- hand over the cargo cmd (e.g. build --release)
- optional: set an env variable which contains a git commit id/branch/tag for the rust repo to checkout before compiling (default: stable)

**Example usage:**

```
docker run \
    --volume <my rust project directory>:/home/cross/project  \
    --volume <.deb dependency dir>:/home/cross/deps \ # optional
    --env RUST_VERSION=<git reference e.g.: "nightly"> \ # optional
    rust-pi-cross \ # name of created docker image
    release --build
```

What do u think about it? In the next couple of days i want to implement this idea for my own project and if u r interested i can make a pull request... 

Any comments/improvement suggestions welcome!

**Comment by Ogeon** [comment]
I have absolutely no experience with Docker, myself, so I may not be able to maintain it or verify its correctness, but I can learn. It doesn't seem too hard. I do like the idea and I think it can be added as an alternative method. What do you think about making a pull request and discussing it as we go?

**Comment by junactl** [comment]
I opened up a pull request in #6. Please let me know what u think.
